### ISSUE TITLE
RuneMonk Entityviewer not working?

### ISSUE THREAD

**Issue by pepijnverburg** [Dezinater/runemonk-recorder#1] opened 2023-02-22 22:27 UTC
Hi there, first of all thanks for the nice plugin. Perhaps a bit unrelated to the plugin itself, but it seems that RuneMonk is not fully working anymore? Are you also the maintainer of RuneMonk.com or do you have an idea how to contact the maintainer?

Various people within the RuneLite dev community have been using the great tools regularly :) Thanks in advance and close this issue if you don't have any knowledge the questions above.

For example some of the NPC/item/object definition fetching is not working anymore:
<img width="613" alt="Screen Shot 2023-02-22 at 23 26 37" src="https://user-images.githubusercontent.com/15874104/220774133-780503c6-e7a6-4753-89ca-86b0f47f8b90.png">

**Comment by Dezinater** [comment] 2023-02-23 01:51
Hey thanks for bringing up this issue. I actually wasn't even aware people from the RuneLite community were using RuneMonk. I'm not even sure how you guys have found RuneMonk haha

The site has been fixed it should work now. It should be using the latest cache now too

**Comment by pepijnverburg** [comment] 2023-02-23 14:36
Great to know that you are the maintainer, awesome tools! It is the best one out there to preview models, play animations and lookup its additional data. Thanks for that. Some of us found it via googling for 'OSRS model viewer' or something, at least how I found it.

I just tested and it still looks broken for me, but now with different errors somehow? I tried hard-refreshing to force reloading all the assets or different browsers, but to no avail :( See attached screenshot with the current errors (Chrome):

<img width="630" alt="Screen Shot 2023-02-23 at 15 33 59" src="https://user-images.githubusercontent.com/15874104/220937538-14052e78-71d0-43f2-bc83-390be36fd855.png">

**Comment by Dezinater** [comment] 2023-02-24 04:06
Thank you for using it :) I wasn't advertising this site or really giving it out yet because of issues like this. I think this is a caching issue maybe with CloudFlare, but I haven't been able to fully look in to it yet. Me and my friend were able to load the site but I'll test with more people tomorrow. But it might be kinda hard to debug it without being able to reproduce this error on my end

Are you able to see how big osrsentityviewer.js is? It should be 425kb. I just added code for loading items from the new cache last night so if it's getting stuck there I'm guessing its not loading the new code. main_file_cache.dat2 should be around 116mb

**Comment by pepijnverburg** [comment] 2023-02-24 10:47
It does look like it was fixed! Perhaps a CloudFlare cahing issue indeed. I did try it out over the course of multiple hours (around 10 loads with caching enabled, 10 page loads without caching disabled AND on different browsers), so probably one of those 'caching on the edge' features. See screenshots attached where errors in the console are now gone, the file `osrsentityviewer.js` is still quite small though as can be seen in the screenshot.

<img width="1546" alt="Screen Shot 2023-02-24 at 11 43 24" src="https://user-images.githubusercontent.com/15874104/221159282-d3ae05fe-7538-451e-b61d-974ac741f3a6.png">

<img width="625" alt="Screen Shot 2023-02-24 at 11 43 56" src="https://user-images.githubusercontent.com/15874104/221159396-a0333bd9-711e-4aa2-8659-f462a6cdf7de.png">

**Comment by Dezinater** [comment] 2023-02-24 11:46
I'm glad to hear it was a caching related issue and it's working again. What's weird to me is that it seems like you were sent the newer cache but not the new code even though I updated both of them at the same time and I did clear the cloudflare cache right after updating the site. Maybe I just need to setup cloudflare better

I think that 103kb size is the compressed size if you hover over that number it will show the real size I think. Or you could save the file and see the size

It seems like this issue is fixed now but I'll leave this open for a bit incase it happens to anyone else still. Also maybe I should make a proper RuneMonk project on here so people have a spot to report issue and discuss future updates

**Closed as completed** 2023-04-16 04:27 UTC

**Comment by pepijnverburg** [comment] 2023-04-16 09:46
Forgot to mention: a dedicated project (/open sourcing?) is a good idea :) Not sure how widespread the usage of the tool is of course. I don't know if you have traffic data available? but that could inform you whether it is worth the effort. Nevertheless, thanks again for the great tool!

**Comment by Dezinater** [comment] 2023-04-17 18:12
I do plan on open sourcing this in the future but for now it's too unstable to use reliably. Usually when the cache updates something breaks in the code and there's a very rare error that I think is coming from the decompression libraries. The code is also going thru alot of changes which might break other peoples code if they were to depend on this project right now. So my main goals before release are finding and fixing reading bugs so that new caches automatically work and having a consistent library api so that as the code is updated older projects depending on this will still work. I've started the process of converting to Typescript and adding tests to prepare for the open source release.

As for traffic it's hard for me to tell just from the logs cause I'm not sure how many are bots and how many are actually using the site. I didn't even know too many people used it before you posted this issue haha. I even set up a discord to get an estimate of how many people are interested in it but no one's really joined from the site so far. So it's very hard for me to tell how many people really use it lol

**Comment by pepijnverburg** [comment] 2023-05-04 15:33
Ah you update the cache automatically, I thought perhaps it is a manual process. Traffic would be a good metric, Discord joins is not really representative. Probably tracking how often the cache is being actually loaded can filter out the bots a bit (due to this being a 100MB download if I remember correctly). Wouldn't put too much effort in open-sourcing it if you don't have a good idea on how much it is used. I just know multiple people in the RL dev scene and I send over the  website when people need some model/animation previewing. 

I did make a working local copy btw of the Entityviewer just to have it available in case a cache update breaks something ;) Needed some minor fiddling in the JS, but it works nicely now.

**Comment by Dezinater** [comment] 2023-05-06 14:13
The cache doesn't update automatically just yet there's one bug that's stopping me from doing that. But this is also related to the open sourcing effort since I want the package fully stable before releasing it. 

Honestly I guess the traffic doesn't even matter too much. The main thing the traffic stuff was about was getting insights from the users but I think having the discord linked is good enough. If people want specific areas worked on now there's a proper way for them to say so instead of looking at traffic and guessing. 

I can add some changes to the entityviewer to make it easier to share links for you

Someone else was able to get a local copy working too. Was it hard to get it working? Is there anything that can be done to make it easier? There is also a web loader included too but it's not completely implemented yet. It should be very easy to use once that is added in

Also RuneMonk should always work, there should never be a time a broken cache is loaded onto there. Even when the automatic cache updating is added it should be able to test the cache and see if it works before using it

**Comment by pepijnverburg** [comment] 2023-05-18 23:13
Thanks for the extra info! Making the local copy was quite easy, only needed to change the absolute paths in the JS files with the runemonk domain name to relative ones so it loads the correct files locally (if I remember correctly).
